version: 2

models:
  - name: int_mlflow_runs
    description: "MLflow runs with metrics and params joined"
    columns:
      - name: run_uuid
        tests:
          - unique
          - not_null

  - name: int_optuna_trials
    description: "Optuna trials with parameters and values"
    columns:
      - name: trial_id
        tests:
          - unique
          - not_null
