name: "crypto_trading_lakehouse"
version: "1.0.0"
config-version: 2

profile: "crypto_trading_lakehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

tests:
  crypto_trading_lakehouse:
    +severity: warn

models:
  crypto_trading_lakehouse:
    +materialized: table
    +schema: main
    bronze:
      +tags: ["bronze"]
    silver:
      +tags: ["silver"]
    gold:
      +tags: ["gold"]

seeds:
  crypto_trading_lakehouse:
    +schema: crypto_ref

